language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
sudo: false
osx_image: xcode6.4
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - binutils-dev
    - g++-4.7

env:
  ## All these variables are sent into the bin/test_travis.sh script. See this
  ## script to know how they are used. Most of them are just passed to cmake,
  ## so if they are not set, cmake will use a default value. For the rest, the
  ## bin/test_travis.sh script usually checks for either "yes" or "no" in an if
  ## statement, so if the variable is not set, the other if branch will get
  ## executed.
  matrix:
  # Debug builds:
  - BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="3.6" TEST_SYMPY="yes"

  # Release builds:
  - PYTHON_VERSION="3.7" WITH_MPC="yes"
  - PYTHON_VERSION="3.7" WITH_MPFR="yes"
  - PYTHON_VERSION="3.6" WITH_MPC="yes" INTEGER_CLASS="flint" WITH_FLINT="yes"

matrix:
  exclude:
    - compiler: clang
    - os: osx
  include:
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" WITH_PIRANHA="yes" PYTHON_VERSION="3.7"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - binutils-dev
          - g++-4.8
    - env: BUILD_TYPE="Debug" WITH_BFD="yes" PYTHON_VERSION="3.8" BUILD_SHARED_LIBS="yes"
      compiler: clang
      os: linux
    - env: BUILD_TYPE="Debug" PYTHON_VERSION="3.6" WITH_SYMPY="no" WITH_LLVM="8.0" WITH_SCIPY="yes" CC="gcc-4.8" CXX="g++-4.8"
      compiler: gcc
      os: linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-8
          packages:
          - g++-4.8
          - libstdc++-4.8-dev
          - binutils-dev
          - llvm-8-dev
    - env: BUILD_TYPE="Debug" PYTHON_VERSION="3.7" WITH_LLVM="5.0" WITH_SCIPY="yes"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Release" PYTHON_VERSION="3.5" WITH_NUMPY="no"
      compiler: clang
      os: osx
    - env: BUILD_TYPE="Debug" PYTHON_VERSION="3.6" WITH_NUMPY="no"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release" PYTHON_VERSION="3.6"
      compiler: gcc
      os: osx
    - env: BUILD_TYPE="Release" WITH_SAGE="yes" WITH_MPC="yes" PYTHON_VERSION="3.8"
      compiler: gcc
      os: linux

before_install:
- |
   if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
     command curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
     rvm get head || true
   fi

install:
  - export PYTHON_SOURCE_DIR=`pwd`
  - export TEST_CPP="no"
  - export MAKEFLAGS="-j2"

  - git clone https://github.com/symengine/symengine symengine-cpp
  - cd symengine-cpp
  - export SOURCE_DIR=`pwd`
  - git checkout `cat ../symengine_version.txt`
  - cd ..

  # Setup travis for C++ library
  - cd $SOURCE_DIR
  - source bin/install_travis.sh

  # Setup travis for Python wrappers
  - cd $PYTHON_SOURCE_DIR
  - source bin/install_travis.sh

  # Build C++ library
  - cd $SOURCE_DIR
  - bin/test_travis.sh
  - unset MAKEFLAGS

script:
  # Build Python wrappers and test
  - cd $PYTHON_SOURCE_DIR
  - bin/test_travis.sh

notifications:
  email: false

